/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smarttermo;

import java.awt.event.ActionEvent;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Turma A
 */
public class SmartTermo extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    double temp = 25;
    double tempD = 25;
    double humidade = 60;
    double hD = 60;
    boolean On = true;

    public SmartTermo() {
        initComponents();
        jLabelTemp.setText("Current Temp: " + temp);
        jLabelTempDes.setText("Desired Temp: " + tempD);
        jLabelH.setText("H: " + humidade);
        jLabelHD.setText("DH: " + hD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTemp = new javax.swing.JLabel();
        jLabelTempDes = new javax.swing.JLabel();
        jLabelH = new javax.swing.JLabel();
        jLabelHD = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jButtonTempMenos = new javax.swing.JButton();
        jButtonTempMais = new javax.swing.JButton();
        jButtonHMenos = new javax.swing.JButton();
        jButtonHMais = new javax.swing.JButton();
        jButtonFahrenheit = new javax.swing.JButton();
        jButtonCelsius = new javax.swing.JButton();
        jButtonOnOff = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTemp.setText("Current Temp: ");

        jLabelTempDes.setText("Desired Temp: ");

        jLabelH.setText("H: ");

        jLabelHD.setText("DH: ");

        jLabelData.setText("jLabel5");

        jButtonTempMenos.setText("-");
        jButtonTempMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTempMenosActionPerformed(evt);
            }
        });

        jButtonTempMais.setText("+");
        jButtonTempMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTempMaisActionPerformed(evt);
            }
        });

        jButtonHMenos.setText("-");
        jButtonHMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHMenosActionPerformed(evt);
            }
        });

        jButtonHMais.setText("+");
        jButtonHMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHMaisActionPerformed(evt);
            }
        });

        jButtonFahrenheit.setText("Fº");

        jButtonCelsius.setText("Cº");

        jButtonOnOff.setText("ON");
        jButtonOnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOnOffActionPerformed(evt);
            }
        });

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTempDes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelHD))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTemp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelH)))
                        .addGap(173, 173, 173))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonFahrenheit)
                                .addGap(90, 90, 90)
                                .addComponent(jButtonCelsius)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonOnOff))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonTempMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonTempMais, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                .addComponent(jButtonHMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonHMais, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(104, 104, 104))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelData)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFahrenheit)
                    .addComponent(jButtonCelsius)
                    .addComponent(jButtonOnOff))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTemp)
                    .addComponent(jLabelH))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTempDes)
                    .addComponent(jLabelHD))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTempMenos)
                    .addComponent(jButtonTempMais)
                    .addComponent(jButtonHMenos)
                    .addComponent(jButtonHMais))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTempMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTempMenosActionPerformed
        // TODO add your handling code here:
        tempD = tempD - 0.5;
        jLabelTempDes.setText("Desired Temp: " + tempD);
        jTextAreaLog.append("Diminuiu a temperatura 0.5 graus");
    }//GEN-LAST:event_jButtonTempMenosActionPerformed

    private void jButtonTempMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTempMaisActionPerformed
        // TODO add your handling code here:
        tempD = tempD + 0.5;
        jLabelTempDes.setText("Desired Temp: " + tempD);
    }//GEN-LAST:event_jButtonTempMaisActionPerformed

    private void jButtonHMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHMenosActionPerformed
        // TODO add your handling code here:
        hD = hD - 5;
        jLabelHD.setText("DH: " + hD);
    }//GEN-LAST:event_jButtonHMenosActionPerformed

    private void jButtonHMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHMaisActionPerformed
        // TODO add your handling code here:
        hD = hD + 5;
        jLabelHD.setText("DH: " + hD);
    }//GEN-LAST:event_jButtonHMaisActionPerformed

    private void jButtonOnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOnOffActionPerformed
        // TODO add your handling code here:
        if (On = true) {
            On = false;
            jButtonOnOff.setText("Off");
            jLabelTempDes.setEnabled(false);
            jLabelHD.setEnabled(false);
        }
        else{
            On = true;
            jButtonOnOff.setText("On");
            jLabelTempDes.setEnabled(true);
            jLabelHD.setEnabled(true);
            //jLabelTempDes.setText("Desired Temp: " + tempD);
            //jLabelHD.setText("DH: " + hD);
        }

    }//GEN-LAST:event_jButtonOnOffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartTermo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCelsius;
    private javax.swing.JButton jButtonFahrenheit;
    private javax.swing.JButton jButtonHMais;
    private javax.swing.JButton jButtonHMenos;
    private javax.swing.JButton jButtonOnOff;
    private javax.swing.JButton jButtonTempMais;
    private javax.swing.JButton jButtonTempMenos;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelH;
    private javax.swing.JLabel jLabelHD;
    private javax.swing.JLabel jLabelTemp;
    private javax.swing.JLabel jLabelTempDes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaLog;
    // End of variables declaration//GEN-END:variables

    JLabel getJLabelTemp() {
        return this.jLabelTemp;
    }

    JLabel getJLabelTempDes() {
        return this.jLabelTempDes;
    }

    public void actionPerformed(ActionEvent e) {

    }
    private void simulateCurretTemp(){
        Timer timer = new Timer();
    
    TimerTask timerTask = new TimerTask(){
        @Override
        public void run(){
            temp= Math.random()*30;
            jLabelTemp.setText(temp +"º");
        }
        
    };
    timer.scheduleAtFixedRate(timerTask, 0, 1000);
    }
    

}
